### ISSUE TITLE
Exception in System.Drawing.SafeNativeMethods.Gdip.CheckStatus

### ISSUE THREAD

**Issue by GuruGurra** [CoreCompat/libgdiplus-packaging#11]
When calling Bitmap.SetResolution() I get the following error on a Mac:

Exception:System.ArgumentException: Parameter is not valid.
   at System.Drawing.SafeNativeMethods.Gdip.CheckStatus(Int32 status)
   at System.Drawing.Bitmap.SetResolution(Single xDpi, Single yDpi)
   at StreamDeck_Midi.ImageController.ResizeImage(Image image, Int32 width, Int32 height) in C:\Projects\StreamDeck-Midi - Core\StreamDeck-Midi\Translation\ImageController.cs:line 424
   at StreamDeck_Midi.ImageController.GetCustomSliderImage(String baseImagePath, String sliderImagePath, Int32 positionPercent, eFaderButtonType FaderButtonType, Int32 paddingTop, Int32 paddingBottom, String& newbaseImagePath, String& newsliderImagePath) in C:\Projects\StreamDeck-Midi - Core\StreamDeck-Midi\Translation\ImageController.cs:line 341

The call works without problems in Windows.

I'm confused by the state of this project.

I'm using the latest release Nuget package (5.8.64) that is published June 26, 2019, but according to this page, there are "No releases published" and "No packages published"?  Looking at the build.yaml, there should be a version 6.0.5, but it's not available at Nuget(?)

**Comment by qmfrederik** [comment]
You can give 6.0.5.128 a try, which has been published on NuGet today.

But [`Bitmap.SetResolution`](https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/libraries/System.Drawing.Common/src/System/Drawing/Bitmap.cs#L328-L332) is just a tiny wrapper around [`GdipBitmapSetResolution`](https://github.com/mono/libgdiplus/blob/main/src/bitmap.c#L2186-L2198), and it doesn't look like that method has changed much the last 10 years or so :-).
